"""Synthetic test dataset generator for EvalOps.

Generates attributed evaluation test cases (EvalTestCase) for an agent based on its
system prompt, role, and domain context using LiteLLM/Model Registry completions.
"""

import json
import logging
import uuid
from typing import Any, Dict, List, Optional
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from common.clients.litellm import completion_with_fallback
from common.models.database import AgentDefinition, EvalTestSuite, EvalTestCase

logger = logging.getLogger("evalops.synthetic")

SYNTHETIC_PROMPT_TEMPLATE = """You are an expert AI Benchmark Engineer.
Generate {count} diverse, high-quality, realistic test queries for evaluating an AI Agent.

Agent Role: {role}
Agent System Prompt: {system_prompt}

Generate exactly {count} evaluation test cases. Output ONLY a valid JSON array where each object has:
- "input_query": A user prompt or question targeting this agent's capabilities.
- "expected_output": A high-quality ground truth expected response.
- "expected_context": Key background context or facts expected to be retrieved/referenced.

Output JSON format strictly:
[
  {{
    "input_query": "...",
    "expected_output": "...",
    "expected_context": "..."
  }}
]
Do not include any extra markdown formatting outside the JSON array.
"""


async def generate_synthetic_test_cases(
    db: AsyncSession,
    agent_id: str,
    count: int = 10,
    system_prompt: Optional[str] = None,
    role: Optional[str] = None,
    model_id: str = "gemini/gemini-3.5-flash"
) -> Dict[str, Any]:
    """Generates synthetic test cases for an Agent and persists them to the database.

    Args:
        db: SQLAlchemy AsyncSession.
        agent_id: ID of the agent definition.
        count: Number of synthetic test cases to generate (default 10).
        system_prompt: Optional prompt override (fetched from DB if omitted).
        role: Optional role override (fetched from DB if omitted).
        model_id: LLM model to use for test generation.

    Returns:
        Dict containing suite_id, agent_id, and created test_cases.
    """
    agent_name = "Agent"
    if not system_prompt or not role:
        stmt = select(AgentDefinition).filter(AgentDefinition.id == agent_id)
        res = await db.execute(stmt)
        agent = res.scalar_one_or_none()
        if not agent:
            system_prompt = system_prompt or "You are a helpful AI assistant."
            role = role or "General Assistant"
            agent_name = f"Agent_{agent_id[:8]}"
        else:
            system_prompt = system_prompt or agent.system_prompt
            role = role or agent.role
            agent_name = agent.name

    prompt = SYNTHETIC_PROMPT_TEMPLATE.format(
        count=count,
        role=role,
        system_prompt=system_prompt
    )

    try:
        response = await completion_with_fallback(
            model=model_id,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=2048,
        )
        content = response.choices[0].message.content.strip()
        if content.startswith("```"):
            lines = content.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            content = "\n".join(lines).strip()

        raw_cases = json.loads(content)
        if not isinstance(raw_cases, list):
            raise ValueError("LLM response did not return a JSON array.")
    except Exception as e:
        logger.warning(f"Synthetic generation LLM call failed or returned invalid JSON: {e}. Generating fallback test set.")
        raw_cases = [
            {
                "input_query": f"Sample evaluation query #{i+1} for {role}",
                "expected_output": f"Expected response for query #{i+1} matching system prompt guidelines.",
                "expected_context": f"Relevant context for query #{i+1}."
            }
            for i in range(min(count, 5))
        ]

    # Look up or create EvalTestSuite for agent
    suite_stmt = select(EvalTestSuite).filter(EvalTestSuite.agent_id == agent_id)
    suite_res = await db.execute(suite_stmt)
    suite = suite_res.scalar_one_or_none()

    if not suite:
        suite = EvalTestSuite(
            id=str(uuid.uuid4()),
            agent_id=agent_id,
            name=f"{agent_name} Synthetic Test Suite",
            description=f"Autogenerated synthetic benchmark suite for agent {agent_id}"
        )
        db.add(suite)
        await db.commit()
        await db.refresh(suite)

    created_cases = []
    for item in raw_cases:
        case = EvalTestCase(
            id=str(uuid.uuid4()),
            suite_id=suite.id,
            input_query=str(item.get("input_query", "")),
            expected_output=str(item.get("expected_output", "")),
            expected_context=str(item.get("expected_context", ""))
        )
        db.add(case)
        created_cases.append(case)

    await db.commit()

    return {
        "status": "success",
        "suite_id": suite.id,
        "agent_id": agent_id,
        "count": len(created_cases),
        "test_cases": [
            {
                "id": c.id,
                "input_query": c.input_query,
                "expected_output": c.expected_output,
                "expected_context": c.expected_context
            }
            for c in created_cases
        ]
    }
